name: Crawl episodes

on:
  issue_comment:
    types: [created]  # for convenient test
  schedule:
    - cron: '*/30 * * * *'

jobs:
  crawl_setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
    - name: Install espeak
      run: sudo apt-get update && sudo apt-get install -y espeak libespeak-dev
    - name: Install dependencies
      run: |
        python3.7 -m venv venv
        source venv/bin/activate
        pip install -r src/tools/requirements.txt
    - name: Install aeneas
      run: |
        source venv/bin/activate
        pip install -e git+https://github.com/anig1scur/aeneas.git@master#egg=aeneas
    - name: Cache venv
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}

  crawl_episode:
    needs: crawl_setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: 6mins
            script: six_mins_english_crawler.py
          - type: tfts
            script: think_fast_talk_smart_crawler.py
          - type: sciam
            script: scientific_american_crawler.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Restore venv
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
    - name: Crawl latest episode data
      run: |
        source venv/bin/activate
        python src/tools/${{ matrix.script }}
    - name: Download audio and extract wave peaks and fragments
      env:
        GITHUB_ACTIONS: true
        TYPE: ${{ matrix.type }}
      run: |
        source venv/bin/activate
        python src/tools/download_audio_and_extract_wave_peaks_and_fragments.py
