name: Crawl episodes

on:
  issue_comment:
    types: [created]  # for convenient test
  schedule:
    - cron: '*/30 * * * *'

jobs:
  crawl_audios:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [6mins, tfts, sciam]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # numpy 和 aeneas 好似有一些依赖问题。用最新的 Python 有奇怪 bug 不查了。
        # https://github.com/readbeyond/aeneas/issues/306
        python-version: '3.7'
    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
    - name: Install espeak
      run: sudo apt-get update && sudo apt-get install -y espeak libespeak-dev
    - name: Install dependencies
      run: |
        python3.7 -m venv venv
        source venv/bin/activate
        pip install -r src/tools/requirements.txt
    - name: Install aeneas
      run: |
        source venv/bin/activate
        pip install -e git+https://github.com/anig1scur/aeneas.git@master#egg=aeneas
    - name: Crawl latest episode data
      run: |
        source venv/bin/activate

        if [ "${{ matrix.type }}" == "6mins" ]; then
          python src/tools/six_mins_english_crawler.py
        elif [ "${{ matrix.type }}" == "tfts" ]; then
          python src/tools/think_fast_talk_smart_crawler.py
        else
          python src/tools/scientific_american_crawler.py
        fi
    - name: Download audio and extract wave peaks and fragments
      env:
        GITHUB_ACTIONS: true
        TYPE: ${{ matrix.type }}
      run: |
        source venv/bin/activate
        python src/tools/download_audio_and_extract_wave_peaks_and_fragments.py
